### ISSUE TITLE
CFURLRequestSetHTTPCookieStorageAcceptPolicy_block_invoke

### ISSUE THREAD

**Issue by jsiegers** [akeru-inc/xcnotary#14]
Today when I used xcnotary I got this error. 

```
Notarize
Processing...

✔ Perform check: Developer ID signing
✔ Uploading to notarization service

Notarization status check failed:
2021-04-08 15:44:03.695 altool[89058:478472] CFURLRequestSetHTTPCookieStorageAcceptPolicy_block_invoke: no longer implemented and should not be called

```

I got an email from Apple saying the package was successfully notarized. 
Is this something Apple should fix or is it part of xcnotary?

**Comment by davidvartan** [comment]
Hi,
Thanks for the report.

Looking at https://developer.apple.com/forums/thread/657090?page=2 it appears that particular error is noise, potentially specific to M1 Macs. (Are you on a M1 Mac?)

However `altool` did terminate with a non-zero code so it's possible there was more diagnostics output. `altool` returns errors both via `stdout` and `stderr`, I'm actually preparing a patch to capture both and make the reporting a bit more helpful.

Would you mind trying the following?

`xcrun altool --notarization-history -u $USERNAME -p "@keychain:$APP_SPECIFIC_PASSWORD_NAME"`

This will return a list of RequestUUIDs of recent `altool` invocations. Then you can use the UUID from your recent run and try:

`xcrun altool --notarization-info $UUID -u $USERNAME -p "@keychain:$APP_SPECIFIC_PASSWORD_NAME"`

Does this succeed/are you able to get the status?

You can also check if the binary is notarized as follows:
`spctl -v --assess --type exec`

If notarized, you will see something like:

```
HelloWorld.app: accepted
source=Notarized Developer ID
```

Thanks!
David

**Comment by jsiegers** [comment]
Hi David, 

Yes I'm on a M1 Mac.

When I ask for the history I get a list indeed. But it starts with:
```
2021-04-13 15:50:21.745 altool[58521:383957] CFURLRequestSetHTTPCookieStorageAcceptPolicy_block_invoke: no longer implemented and should not be called
```

When I request the UUID status I do get it, but it starts with:

```
2021-04-13 15:59:55.192 altool[58627:389198] CFURLRequestSetHTTPCookieStorageAcceptPolicy_block_invoke: no longer implemented and should not be called
No errors getting notarization info.
```

**Comment by davidvartan** [comment]
I see, so that does appear to be just logging noise from `altool` and can be ignored.

Based on the error in earlier version of your post, could you try adding the `--provider <your team ID>` argument to `xcnotary` to disambiguate? (Team ID found at https://developer.apple.com/account/#/membership/)

**Comment by jsiegers** [comment]
Yes that's already what I did. Took me a while to realize that I had to use `--team-id` for altool.

**Comment by davidvartan** [comment]
Thanks. In that case `xcnotary` needs better output for this scenario instead of failing silently, I will be fixing that.

**Comment by davidvartan** [comment]
Error reporting has been improved in release v0.4.7
