### ISSUE TITLE
Binaries are broken

### ISSUE THREAD

**Issue by kleuter** [akeru-inc/xcnotary#17]
All binaries for the latest release are
- all the same no matter which macos version you download
- not functional / broken

![image](https://user-images.githubusercontent.com/2600624/120007261-00ac4e00-bfda-11eb-82a5-c5025e020af6.png)
![image](https://user-images.githubusercontent.com/2600624/120007653-6c8eb680-bfda-11eb-8425-12db043c3194.png)

**Comment by davidvartan** [comment]
Thanks for the report!
The arm64 file is for M1 Macs. The remaining three files are three identical copies set up that way for Homebrew to pick them up.

What version of macOS do you have?

**Comment by kleuter** [comment]
- All 4 files are exactly of the same gz file (2 464 610 bytes), including the the one for M1 macs.
- After extracting that .gz file, the binary inside is not a valid macOS binary (6 875 880 bytes), some other format I suppose which obviously contains some binary as I can observe in a hex editor.

Manually compiling the app is simple

```
cargo build --release
```

And produces a valid binary. I'm on Catalina & Big Sur, makes no difference.

**Comment by davidvartan** [comment]
Ah yeah, sorry for the miscomm. The M1 one is (for the time being) also an identical copy until GitHub Actions adds M1 build machines. It's just going to run via Rosetta and saves people from building from source when installing via Homebrew.

How are you extracting the file?

e.g.
```
curl -O --location https://github.com/akeru-inc/xcnotary/releases/download/v0.4.8/xcnotary-0.4.8.big_sur.bottle.tar.gz
tar xvzf xcnotary-0.4.8.big_sur.bottle.tar.gz
file xcnotary/0.4.8/bin/xcnotary
```

Outputs "Mach-O 64-bit executable x86_64" and it runs too.

**Comment by kleuter** [comment]
I'm sorry, my fault. I used 7zip on Windows which failed to extract it correctly!
