### ISSUE TITLE
Use "stapler" from path, not /usr/bin/

### ISSUE THREAD

**Issue by arteme** [akeru-inc/xcnotary#18]
I would like to suggest that "stapler" should be looked up from $PATH, not hard-coded to `/usr/bin/stapler`. The reason for this is simply because `altool` and `stapler` can be extracted from XCode for the purposes of building in a VPS, for example, where space is limited and installing a full mammoth of XCode is simply not an option. In these environments, I'm not sure, where `/usr/bin/stapler` comes from, but running it gives:
```
cloudxmac$ /usr/bin/stapler 
xcode-select: error: tool 'stapler' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

Whereas, I have a working copy of `stapler` in path... This is not a problem for `altool` because `xcrun` actually picks up `altool` from path.

**Comment by davidvartan** [comment]
Thanks for the report! Does `/usr/bin/xcrun stapler` work on your system and find the correct version of `stapler`? I can change the invocation to do that instead of hardcoding `/usr/bin/stapler`.

**Comment by arteme** [comment]
Yes, `xcrun stapler` finds a proper working copy of `stapler`.

**Comment by davidvartan** [comment]
I made the change to use `xcrun` to locate `stapler`. You can update by running `brew update &&
brew upgrade akeru-inc/tap/xcnotary`

Thanks!
