### ISSUE TITLE
Can't specify provider for Apple ID account while notarizing

### ISSUE THREAD

**Issue by zhaorui** [akeru-inc/xcnotary#2]
I fail to notarize with xcnotary since my developer account is attatched to mutiple develop teams.
in "xcrun altool", there is an option "-itc_provider" which could specify the provider. 

Here is the error message from xcnotary.
1 package(s) were not uploaded because they had problems:
	/var/folders/16/qpjbykss3fg1ld3_3j0st8480000gn/T/4E9DC4ED-AFDC-492C-97D5-2C702B2513D7/CloudUEM.pkg.itmsp - Error Messages:
		Your Apple ID account is attached to other providers. You will need to specify which provider you intend to submit content to. Please contact us if you have questions or need help. (1627)

**Comment by davidvartan** [comment]
Thank you for the comment. A new `--provider` argument has been added in [v0.3.0](/akeru-inc/xcnotary/releases/v0.3.0) to specify the provider.

If you're using Homebrew, you can update by running `brew update && brew upgrade akeru-inc/tap/xcnotary`
