### ISSUE TITLE
Notarization status polling should guard against Apple Gateway Timeouts (status 504)

### ISSUE THREAD

**Issue by jjcoffman** [akeru-inc/xcnotary#20]
It seems that in my testing sometimes Apple's notarization gateway tends to return a 504. It appears this happens when polling to get the status of a notarization request via altool.

When this happens xcnotary exits with a non-zero exit code. While this is correct, it might be nice to introduce a retry mechanism for scenarios where the response isn't actually a pass/fail of notarization, but some other error which may be transient like a 504. 

I don't think it should retry indefinitely, but a retry or 3 might be helpful to ensure that these edge cases don't result in having to re-run xcnotary when the "failure" isn't actually a failure per-se.

**Comment by jjcoffman** [comment]
It looks like there is a PR related to this issue as well: https://github.com/akeru-inc/xcnotary/pull/19

**Comment by davidvartan** [comment]
Sorry for the slow response.

As I wrote in https://github.com/akeru-inc/xcnotary/pull/19#issuecomment-1037712075 there isn't as much for `xcnotary` to do now given that Apple made a new similar tool with `--wait` functionality.

Under the hood `xcnotary` still uses `altool` which according to Apple is now deprecated.

Would you be able to try their new tool (`man notarytool`), with or without `[--s3-acceleration | --no-s3-acceleration]` flags (described in `man` page) to see if you're still seeing timeouts?

**Comment by davidvartan** [comment]
Closing as `xcnotary` is being deprecated, to be replaced with `xcrun notarytool --wait` as described in https://github.com/akeru-inc/xcnotary/issues/22
