### ISSUE TITLE
altool deprecated and replaced by notarytool

### ISSUE THREAD

**Issue by bradking** [akeru-inc/xcnotary#22]
Notarizing with `xcnotary` now sometimes reports the following warning from `altool`:

> altool has been deprecated and, starting in fall 2023, will no longer be supported by the Apple notary service. You should start using notarytool to notarize your software.

See also the updated [documentation](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow#3087734) from Apple (or this [web archive snapshot](https://web.archive.org/web/20220630085759/https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow#3087734)).

**Comment by davidvartan** [comment]
Thanks! Yeah, people should now just directly be using `xcrun notarytool` with the `--wait` argument to block until completion, which is what the original `altool` was missing for some reason. I've been meaning to archive this repo since (fortunately) there isn't a need for `xcnotary` anymore.

**Comment by bradking** [comment]
Yes.  For reference, a call to `xcnotary` such as

```bash
xcnotary notarize "/path/to/Foo.app" -d "..." -k "..." ...
```

can be replaced with

```bash
ditto -c -k --keepParent "/path/to/Foo.app" "Foo.app.zip"
xcrun notarytool submit "Foo.app.zip" --keychain-profile "my-notarytool-profile" --wait
xcrun stapler staple "/path/to/Foo.app"
```

where the keychain profile was created with

```bash
xcrun notarytool store-credentials "my-notarytool-profile" --apple-id "..." --team-id "..."
```

which prompts for an [app-specific password](https://support.apple.com/en-us/HT204397).  The team id is available from the Apple ID's [membership page](https://developer.apple.com/account/#!/membership).

**Comment by davidvartan** [comment]
Yes, I've been using very similar steps. Glad they finally added this functionality.

I'm archiving the repo and linked to your comment in the README. Thanks
