### ISSUE TITLE
Support .dmg input

### ISSUE THREAD

**Issue by PatTheMav** [akeru-inc/xcnotary#3]
First of all, thanks for the tool - it's quick and easy to use and the code is concise to read, so one can rest easy that it does what is advertised (quite important when handling signing certs and such).

Would it be possible to implement support for DMG files? From what I could gather an app bundle needs be zipped, then uploaded and stapled. The flow is similar for DMGs, except that the bundling into a zip is not necessary:

```
xcrun altool --notarize-app --primary-bundle-id BUNDLE --username AC_USERNAME --asc-provider PROVIDER --file IMAGE.dmg
xcrun altool --notarization-history 0 --username AC_USERNAME --asc-provider PROVIDER
xcrun stapler staple -v IMAGE.dmg
```

I'm not aware of exact pre-check requirements however, but it would be great if DMG is also supported, as `xcnotary` seems like a very no-frills choice for notarization in CI workflows.

**Comment by davidvartan** [comment]
Many thanks for the feedback, so glad the tool is helpful! I should be able to add DMG support sometime this week.

Will have to double-check, but with DMGs, just as currently is with PKGs, it may be only possible to check that code signing is present. Additional bundle-level checks like having specific entitlements are only available for bundle inputs. Something like would may be a recommended flow for packaged inputs:

1. Build your .app bundle
2. `xcnotary precheck` the bundle
3. Build your .pkg (or .dmg)
4. `xcnotary notarize` the .pkg or .dmg (this will pre-check and notarize)

(If there happens to be a way to perform a deeper inspection on a package/DMG without extracting its contents, I'd like to know! Currently doing a `pkgutil --check-signature <pkg>` for packages which provides only the outer check.)

**Comment by PatTheMav** [comment]
Yeah that's absolutely fine - the app bundle is notarized in a previous step anyway, then packaged in a DMG, which is notarized again. I think it's fine if .dmg and .pkg packages don't have any deep checks.

As long as `xcnotary` has a non-zero return value on errors, the CI process will abort accordingly as well.

**Comment by davidvartan** [comment]
Fixed in v0.4.0

Regarding notarizing the bundle and then notarizing the .dmg/.pkg, I am investigating separately with Apple technical support to see what they recommend. As it appears currently, while process does notarize the enclosed .app bundle, it does not staple a ticket to it, i.e. requiring the two-step process similar to what you have.

**Comment by davidvartan** [comment]
@PatTheMav 

You might be interested in the response I got from Apple support re: whether or not the inner bundle needs to be separately notarized:

> Our general advice here is that you sign everything, from the inside out, and then notarise and staple the outermost container.  That ticket covers all the code included in the container.  When Gatekeeper checks the code signature of the container, it will ingest the ticket, avoiding the need for a round trip to the notary service on first run.

**Comment by PatTheMav** [comment]
@davidvartan Thanks for handling this - so do I understand their response right that code signing all binaries/libraries/frameworks, bundling, signing the bundle, packaging into a `.dmg` and signing that `.dmg` should be enough and only that `.dmg` needs to be notarized/stapled?

**Comment by davidvartan** [comment]
@PatTheMav That is correct!
