### ISSUE TITLE
xcnotary notarize error

### ISSUE THREAD

**Issue by chengkeke366** [akeru-inc/xcnotary#9]
With the v4.1 version notarizing .app images works flawlessly, however trying to notarize an app bundle fails with the following message:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorImpl { kind: Serde("missing field `CFBundleVersion`"), file_position: None } }', src/util/plist/mod.rs:6:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

But  I precheck success
 xcnotary precheck ./xxx.app                                                                                         
Processing...

✔ Perform check: Developer ID signing
✔ Perform check: Hardened runtime
✔ Perform check: No get-task-allow entitlement
✔ Perform check: Secure timestamp

**Comment by chengkeke366** [comment]
Looking forward to your reply

**Comment by davidvartan** [comment]
Thanks for the report! Could you double-check if your Info.plist actually has`CFBundleVersion` entry? (https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion)

**Comment by chengkeke366** [comment]
Thank you very much.  I forget  the CFBundleVersion entry and CFBundleShortVersionString entry.

now it work very good！

Thanks again
